### ISSUE TITLE
[Suggestion] Enable "binary_response" to Set a Content Type

### ISSUE THREAD

**Issue by loloicci** [rory/rust-cgi#10]
https://github.com/rory/rust-cgi/blob/269b6680b84bc2645e89ec144f31bbc8b7a4bb2a/src/lib.rs#L218-L228

I suggest enabling `binary_response` to get content type as a parameter and to set it as the response.

**Comment by rory** [comment]
I have added something in ( https://github.com/rory/rust-cgi/commit/2bcd6f2ff5598a784477ad71911be2a1ba709c3d ), where you can specify an 'optional' middle parameter for the content type. Can you check the `binary-content-type` branch: ( https://github.com/rory/rust-cgi/tree/binary-content-type  )

Does that solve your problem?

**Comment by loloicci** [comment]
Excellent!
It solves my problem.

However, it is concerned about backward compatibility.
Although `binary_responce(200, some-data)` works before this patch, it will not work if this is merged.
(I am all right if you do not care.)

**Comment by rory** [comment]
Yes, this is a breaking change. However this library is still at `0.x` version, so breaking changes are allowed according to [Semantic Versioning](https://semver.org/). I do not think this library is (yet!) used a lot, so breaking changes would not be that big of a problem. I'd rather make a good library, than by tied forever to what was done at the start.

**Comment by rory** [comment]
This has been merged in.

**Comment by loloicci** [comment]
Thanks a lot!

**Comment by rory** [comment]
Released in v0.6.0
