### ISSUE TITLE
Set charset in the header

### ISSUE THREAD

**Issue by Unrealrussian** [rory/rust-cgi#14]
Signaling the charset in the header, so that it would interpret the text correctly, as in HTTP 1.1 ISO-8859-1 is the default setting.
Reference: https://www.w3.org/International/articles/http-charset/index#charset 
PR: #13

**Comment by rory** [comment]
This has been merged in https://github.com/rory/rust-cgi/commit/3baaf3efe29c07b36d2c711b28ad258504590b50

**Comment by rory** [comment]
Thanks for your submissions. BTW I don't require that you open an issue for every pull request. You can just open a PR on it's own if you have a patch. 🙂

**Comment by rory** [comment]
Released in v0.6.0
