### ISSUE TITLE
Python command to run CGI server is out of date.

### ISSUE THREAD

**Issue by mvillalba** [rory/rust-cgi#5]
Hi,

Just a quick note to improve the README. The provided Python command to run a test CGI server is out of date. It uses Python 2 which is about to reach EOL. At this point it's safe to assume Python 3 will be installed and available in any modern environment.

I suggest adding the Py3k-equivalent command first, and mentioning the existing Python 2 version for people with old systems.

The command for Python 3 is:

`$ python3 -m http.server --cgi`

Cheers,
Martín

**Comment by rory** [comment]
Thanks! :)
