### ISSUE TITLE
multipart form upload

### ISSUE THREAD

**Issue by JakeChampion** [rory/rust-cgi#7]
Hi, thanks for making this crate!

I'm trying to use this crate with a form upload but can't seem to get the multipart crate to integrate with it. I was wondering/hoping if you have tried this before yourself and/or know whether this is possible?

**Comment by rory** [comment]
Hi. I haven't tried it with this crate, I haven't needed to do that yet.

I would be interested in adding such a feature. 🙂

**Comment by JakeChampion** [comment]
This is the first time I've tried to implement a trait on something (I'm very very new to Rust, only part way through the book).

I tried to add support for it but the Rust compiler got mad at me because the Request type comes from the external http crate so I can't add the trait to it.

>only traits defined in the current crate can be implemented for arbitrary types
define and implement a trait or new type instead rustc(E0117)

This is the code I was writing:
```rust
impl<'r> multipart::server::HttpRequest for &'r mut Request {
    type Body = &'r mut Vec<u8>;
    
    fn multipart_boundary(&self) -> Option<&str> {
        const BOUNDARY: &str = "boundary=";

        let content_type = (self.headers().iter().find(|header| header.field.equiv("Content-Type"))).value.as_str();
        let start = (content_type.find(BOUNDARY)) + BOUNDARY.len();
        let end = content_type[start..].find(';').map_or(content_type.len(), |end| start + end);

        Some(&content_type[start .. end])
    }

    fn body(self) -> Self::Body {
        self.as_reader()
    }
}
```


I'm not sure what we should do here. Should we make our own Request type?

**Comment by JakeChampion** [comment]
I've tried making our own Req type to impl the trait on.

The line `&mut self.body` has an error though:
>the trait bound `std::vec::Vec<u8>: std::io::Read` is not satisfied
required for the cast to the object type `dyn std::io::Read`rustc(E0277)

```rust
pub extern crate multipart;

pub struct Req<T> {
    head: http::request::Parts,
    body: T,
}
/// A `Vec<u8>` Request from http
pub type Request = Req<Vec<u8>>;

impl<'r> multipart::server::HttpRequest for &'r mut Request {
    type Body = &'r mut dyn Read;
    
    fn multipart_boundary(&self) -> Option<&str> {
        const BOUNDARY: &str = "boundary=";

        let content_type = (self.head.headers.iter().find(|header| header.0.as_str().eq("Content-Type"))).unwrap().1.to_str().unwrap();
        let start = (content_type.find(BOUNDARY)).unwrap() + BOUNDARY.len();
        let end = content_type[start..].find(';').map_or(content_type.len(), |end| start + end);

        Some(&content_type[start .. end])
    }

    fn body(self) -> Self::Body {
        &mut self.body
    }
}
```

**Comment by JakeChampion** [comment]
This looks to have no compiler errors!
```rust
pub extern crate multipart;

pub struct Req<T> {
    head: http::request::Parts,
    body: T,
}
/// A `Vec<u8>` Request from http
pub type Request = Req<Vec<u8>>;

impl<'r> multipart::server::HttpRequest for &'r mut Request {
    type Body = &'r mut dyn Read;
    
    fn multipart_boundary(&self) -> Option<&str> {
        const BOUNDARY: &str = "boundary=";

        let content_type = (self.head.headers.iter().find(|header| header.0.as_str().eq("Content-Type"))).unwrap().1.to_str().unwrap();
        let start = (content_type.find(BOUNDARY)).unwrap() + BOUNDARY.len();
        let end = content_type[start..].find(';').map_or(content_type.len(), |end| start + end);

        Some(&content_type[start .. end])
    }

    fn body(self) -> Self::Body {
        &mut &self.body[..]
    }
}
```

**Comment by rory** [comment]
I'm looking at the code now, and the existing libraries to support it. Currently this library will read the entire stdin, i.e. all of the submitted data, and then process it. There is no support for streaming. Lots of the multipart libraries appear to target that use case, and I think that might make things complicated. alas.

**Comment by JakeChampion** [comment]
We could build our own implementation for multipart. I was reading how this person did it in Perl for CGI, it doesn't seem too difficult to do :-) http://www.users.on.net/~bkgunther/software/multipartforms.html

**Comment by rory** [comment]
This library currently doesn't do any parsing of submitted data. It doesn't support multipart form upload directly, but it doesn't support other kinds of 'form parsing'...

**Comment by rory** [comment]
Are you able to share an example of your programme which needs multipart form support? I'm trying to understand how your patch would fix that.

**Comment by rory** [comment]
Since this library doesn't parse any HTTP body (or even the GET params), I am going to close this issue as “out of scope”. If we were to support multipart form uploads, we should support regular POST uploads, & easy GET param access. Perhaps this library should support that, but it doesn't now
